
DROP TABLE IF EXISTS DDRE;
CREATE TABLE DDRE
(
CAT 			VARCHAR(30), 
SUBCAT 			VARCHAR(30), 
REGULAR 		VARCHAR(200)
);


INSERT INTO DDRE VALUES ('EMAIL','EMAIL',"^[A-Za-z][A-Za-z0-9]*@[a-zA-Z0-9]+.(FR|fr|COM|com|[a-zA-Z]+)$");
INSERT INTO DDRE VALUES ('DATE','DATE_FRENCH','^([0-2][0-9]|3[0-1])(-|/)(0[0-9]|1[0-2])(-|/)[0-9]{4}$');
INSERT INTO DDRE VALUES ('DATE','DATE_ENGLISH','^(0[0-9]|1[0-2])(-|/)([0-2][0-9]|3[0-1])(-|/)[0-9]{4}$');
INSERT INTO DDRE VALUES ('CIVILITY','CIVILITY_FR','^(M.|MME|MLLE|MONSIEUR|MADAME|MADEMOISELLE)$');
INSERT INTO DDRE VALUES ('CIVILITY','CIVILITY_EN','^(M.|MRS|MS|MISTER|MISS)$');
INSERT INTO DDRE VALUES ('BLOODGROUP', 'BLOODGROUP', '^((A|B|AB|O){1}[+-]{1})$');
INSERT INTO DDRE VALUES ('TEMPERATURE', 'TEMPERATUREC', '^[0-9][0-9]?°C|[0-9][0-9]?°?CELCIUS|[0-9][0-9]?°?Celcius$');
INSERT INTO DDRE VALUES ('TEMPERATURE', 'TEMPERATUREF', '^[0-9][0-9]?°F|[0-9][0-9]?°?FAHRENHEIT|[0-9][0-9]?°?Fahrenheit$');


COMMIT;

